version: "3.8"

services:
  backend:
    build: 
      context: .
      dockerfile: docker/backend/Dockerfile
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "${FRONTEND_PORT:-5173}:5173"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://backend:8000/api/v1
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
